'use client';
import {useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {flushSync} from 'react-dom';
import {Download,Sparkles,ImagePlus,SlidersHorizontal,Undo2,Redo2,FileText,Check,HelpCircle,X,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {GraphEditor} from '@/components/graph-editor';
import {GraphPreview} from '@/components/graph-preview';
import {ApiKeyDialog} from '@/components/api-key-dialog';
import {StudioFooter} from '@/components/studio-footer';
import {GraphLibrary} from '@/components/graph-library';
import {generateOpenAIGraph} from '@/lib/openai-graph';
import {typesetSvg} from '@/lib/math-svg';
import {presets,renderGraph,defaultStyle,fromCoordinates,graphSchema,type Style,type Graph} from '@/lib/graph';
const thumbnailSvgs=presets.map((p,i)=>renderGraph(p.graph,{...defaultStyle,width:420,height:290,fontSize:18,lineWidth:3},'mini'+i));
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
type WebContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations?:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
export default function Home(){
 const [graph,setGraph]=useState<Graph>(presets[0].graph),[style,setStyle]=useState<Style>(defaultStyle),[prompt,setPrompt]=useState('시간에 따른 전류 그래프를 그려 줘.\n(0, 0)에서 (2, 3)까지 증가하고,\n(4, 1)까지 직선으로 감소해.\n가로축은 시간 t, 세로축은 전류 I로 표시해.');
 const [thumbs,setThumbs]=useState(thumbnailSvgs);
 const [library,setLibrary]=useState(false);
 const libraryButton=useRef<HTMLButtonElement>(null);
 const [tab,setTab]=useState('text'),[image,setImage]=useState<string|null>(null),[fileName,setFileName]=useState(''),[imagePrompt,setImagePrompt]=useState(''),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[apiSettings,setApiSettings]=useState(false),[editor,setEditor]=useState(false),[help,setHelp]=useState(false),[format,setFormat]=useState('svg'),[scale,setScale]=useState('3'),[history,setHistory]=useState<Graph[]>([]),[future,setFuture]=useState<Graph[]>([]),[refine,setRefine]=useState(false);
 const apiKey=useRef('');
 const request=useRef<AbortController|null>(null),fileInput=useRef<HTMLInputElement|null>(null),graphRef=useRef(graph);graphRef.current=graph;
 const svg=useMemo(()=>renderGraph(graph,style),[graph,style]);
 useEffect(()=>{let active=true;Promise.all(thumbnailSvgs.map(s=>typesetSvg(s))).then(rs=>{if(active)setThumbs(rs.map(r=>r.svg));});return()=>{active=false;};},[]);
 const commit=useCallback((next:Graph)=>{setHistory(h=>[...h.slice(-19),graphRef.current]);setFuture([]);setGraph(next);setError('');},[]);
 useEffect(()=>{const clear=()=>{apiKey.current='';request.current?.abort('cancel');setReady(false);};window.addEventListener('pagehide',clear);return()=>{window.removeEventListener('pagehide',clear);apiKey.current='';request.current?.abort();};},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:WebContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'set_exam_graph',description:'Validate and replace the visible editable exam graph using structured graph coordinates, labels, curves and guide lines.',inputSchema:{type:'object',properties:{graph:{type:'object'}},required:['graph'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const parsed=graphSchema.parse((input as {graph:unknown}).graph);flushSync(()=>commit(parsed));return {title:parsed.title,curves:parsed.curves.length};}},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(context.registerTool({name:'read_exam_graph',description:'Read the currently visible exam graph data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return graphRef.current;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[commit]);
 async function generate(){
  if(busy)return;if(!apiKey.current){setApiSettings(true);return;}
  setError('');if(tab==='image'&&!image){setError('먼저 그래프 이미지를 넣어 주세요.');return;}if(tab==='text'&&!prompt.trim()){setError('그릴 그래프를 설명해 주세요.');return;}
  setBusy(true);const controller=new AbortController();request.current=controller;const timer=setTimeout(()=>controller.abort('timeout'),120000);
  try{const next=await generateOpenAIGraph({prompt:tab==='text'?prompt:imagePrompt,...(tab==='image'&&image?{image}:{}),...(refine?{current:graph}:{})},apiKey.current,controller.signal);if(!controller.signal.aborted){commit(next);toast.success('그래프를 만들었습니다.');}}
  catch(e){setError(controller.signal.aborted?(controller.signal.reason==='timeout'?'시간이 초과됐습니다. 설명을 줄여 다시 시도해 주세요.':'생성을 취소했습니다.'):e instanceof Error?e.message:'연결을 확인하고 다시 시도해 주세요.');}
  finally{clearTimeout(timer);setBusy(false);request.current=null;}
 }

 async function loadImage(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('PNG, JPG, WebP 이미지를 사용해 주세요.');return;}if(file.size>10*1024*1024){setError('10 MB 이하의 이미지를 넣어 주세요.');return;}setError('');try{const url=URL.createObjectURL(file);try{const img=new window.Image();img.src=url;await img.decode();const ratio=Math.min(1,1800/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);setImage(canvas.toDataURL('image/jpeg',.92));setFileName(file.name);setTab('image');}finally{URL.revokeObjectURL(url);}}catch{setError('이미지를 열 수 없습니다. 다른 파일로 시도해 주세요.');}}
 function undo(){if(!history.length)return;setFuture(f=>[graph,...f]);setGraph(history[history.length-1]);setHistory(h=>h.slice(0,-1));}
 function redo(){if(!future.length)return;setHistory(h=>[...h,graph]);setGraph(future[0]);setFuture(f=>f.slice(1));}
 async function download(){setExporting(true);try{const rendered=await typesetSvg(svg);if(rendered.errors.length)throw Error('수식 문법을 확인해 주세요.');const finalSvg=rendered.svg;const name=(graph.title||'시험지 그래프').replace(/[\\/:*?"<>|]/g,'-');if(format==='svg'){saveBlob(new Blob([finalSvg],{type:'image/svg+xml;charset=utf-8'}),name+'.svg');}else{await document.fonts.ready;const url=URL.createObjectURL(new Blob([finalSvg],{type:'image/svg+xml'}));try{const img=new window.Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=style.width*Number(scale);canvas.height=style.height*Number(scale);const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error()),'image/png'));saveBlob(blob,name+'.png');}finally{URL.revokeObjectURL(url);}}toast.success('그래프를 다운로드했습니다.');}catch(e){toast.error(e instanceof Error?e.message:'저장하지 못했습니다. 다시 시도해 주세요.');}finally{setExporting(false);}}
 return <div className="app"><Toaster position="bottom-center"/><header className="header"><div className="brand"><span className="brand-mark">∿</span><strong>도해<span>GRAPH STUDIO</span></strong></div><div className="header-center">시험지 그래프 작업실</div><div className="header-actions"><button className="button api-settings-button" disabled={busy} onClick={()=>setApiSettings(true)}>{ready?'✓ 내 API 연결됨':'내 API 연결'}</button><button className="icon-button" aria-label="사용 방법" onClick={()=>setHelp(true)}><HelpCircle size={19}/></button><button className="button" onClick={download} disabled={exporting}>{exporting?<LoaderCircle className="spin" size={16}/>:<Download size={16}/>} {format.toUpperCase()} 다운로드</button></div></header>
 <main className="workspace"><aside className="input-panel"><div className="panel-heading"><span className="eyebrow">01 · INPUT</span><h1>어떤 그래프를 그릴까요?</h1><p>설명이나 그림을, 깔끔한 시험지 그래프로.</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="input-tabs"><TabsTrigger value="text" disabled={busy}><FileText/>설명 입력</TabsTrigger><TabsTrigger value="image" disabled={busy}><ImagePlus/>이미지 첨부</TabsTrigger></TabsList><TabsContent value="text"><label className="field-label" htmlFor="prompt">그래프 설명</label><textarea id="prompt" maxLength={6000} disabled={busy} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="예: y = x², -2부터 2까지. 꼭짓점과 x=1에 점선을 표시해 줘."/><p className="hint">축 이름, 좌표, 선의 모양을 함께 적어 주세요.</p></TabsContent><TabsContent value="image"><div className={'upload-box '+(image?'has-image':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])void loadImage(e.dataTransfer.files[0]);}} onPaste={e=>{const f=Array.from(e.clipboardData.files)[0];if(f&&!busy){e.preventDefault();void loadImage(f);}}} tabIndex={0} aria-label="이미지 파일을 끌어놓거나 붙여넣기"><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" aria-label="그래프 이미지 파일" className="sr-only" disabled={busy} onChange={e=>{if(e.target.files?.[0])void loadImage(e.target.files[0]);e.target.value='';}}/>{image?<><img src={image} alt="업로드한 원본 그래프"/><span className="upload-name">{fileName}</span><div className="image-actions"><button className="text-button" disabled={busy} onClick={()=>fileInput.current?.click()}>다른 이미지</button><button className="icon-button" disabled={busy} aria-label="첨부 이미지 삭제" onClick={()=>{setImage(null);setFileName('');}}><X size={15}/></button></div></>:<><ImagePlus size={28}/><b>그림을 끌어다 놓으세요</b><span>PNG, JPG, WebP · 최대 10 MB<br/>클릭 후 ⌘V / Ctrl+V로 붙여넣기</span><button className="button" disabled={busy} onClick={()=>fileInput.current?.click()}>파일 선택</button></>}</div><label className="field-label image-prompt">추가 요청 <span className="optional">선택</span><textarea disabled={busy} maxLength={6000} rows={3} value={imagePrompt} onChange={e=>setImagePrompt(e.target.value)} placeholder="예: 점선을 유지하고, 가로축 이름을 시간으로 바꿔 줘."/></label><p className="hint">이미지는 그래프 해석을 위해 OpenAI에 전송됩니다.</p></TabsContent></Tabs>
 <label className="switch-row refine-switch">현재 그래프를 수정하기<Switch disabled={busy} size="sm" checked={refine} onCheckedChange={setRefine}/></label><button className="button primary full" onClick={generate} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'그래프 해석 중…':!ready?'API 연결하고 만들기':refine?'요청대로 수정하기':'그래프 만들기'}</button>{busy&&<button className="text-button cancel-generation" onClick={()=>request.current?.abort('cancel')}>생성 취소</button>}{ready===false&&<div className="notice">AI 생성은 본인 OpenAI API 키로 이용합니다. 예시·좌표 편집·다운로드는 키 없이 사용할 수 있습니다.</div>}{error&&<div className="error" role="alert">{error}</div>}{tab==='text'&&<button className="text-button coordinate-button" disabled={busy} onClick={()=>{try{commit(graphSchema.parse(fromCoordinates(prompt)));toast.success('입력한 좌표를 연결했습니다.');}catch(e){setError(e instanceof Error?e.message:'좌표를 확인해 주세요.');}}}>좌표만 바로 그리기 <span>AI 없이</span></button>}
 <div className="examples-head"><h2>예시에서 시작하기</h2><span>8가지</span></div><div className="preset-grid">{presets.map((p,i)=><button key={p.id} disabled={busy} title={p.description} className={'preset '+(graph.title===p.graph.title?'active':'')} onClick={()=>{commit(structuredClone(p.graph));setRefine(false);}}><div className="mini-graph" dangerouslySetInnerHTML={{__html:thumbs[i]}}/><span>{p.name}</span></button>)}</div><button ref={libraryButton} className="button full library-open" disabled={busy} onClick={()=>setLibrary(true)}><FileText size={17}/><span>기출 유형 20개 둘러보기<small>과학탐구Ⅰ·Ⅱ · 최근 5개년</small></span><span aria-hidden="true">↗</span></button><div className="input-footer"><span className="tiny-axis">↗</span>선은 정확하게, 표현은 간결하게.</div></aside>
 <section className="canvas-panel" aria-busy={busy}><div className="canvas-header"><div><span className="eyebrow">02 · PREVIEW</span><h2>{graph.title}</h2></div><span className="badge"><Check size={13}/>KaTeX · 벡터</span></div><div className="canvas-area"><GraphPreview graph={graph} style={style} disabled={busy} onCommit={commit} onDropImage={loadImage}/>{graph.note&&<p className="graph-note">{graph.note}</p>}</div><div className="canvas-bottom"><div className="history-buttons"><button className="icon-button" disabled={!history.length||busy} onClick={undo} aria-label="그래프 실행 취소"><Undo2 size={16}/></button><button className="icon-button" disabled={!future.length||busy} onClick={redo} aria-label="그래프 다시 실행"><Redo2 size={16}/></button><span>생성 결과의 수치와 기호를 확인해 주세요.</span></div><button className="text-button" onClick={()=>setStyle(defaultStyle)}><Undo2 size={15}/>스타일 초기화</button></div></section>
 <aside className="settings-panel"><div className="settings-title"><SlidersHorizontal size={18}/><h2>그래프 다듬기</h2></div><section className="setting-section"><h3>축과 이름</h3><label className="field-label">가로축<input disabled={busy} maxLength={80} value={graph.xLabel} onChange={e=>setGraph({...graph,xLabel:e.target.value})}/></label><label className="field-label">세로축<textarea disabled={busy} rows={2} maxLength={80} value={graph.yLabel} onChange={e=>setGraph({...graph,yLabel:e.target.value})}/></label><p className="hint">{'KaTeX: I_0 · t_0 · \\frac{1}{2}'}</p><button className="button full edit-button" disabled={busy} onClick={()=>setEditor(true)}><SlidersHorizontal size={14}/>좌표·눈금·문자 편집</button></section><section className="setting-section"><h3>선과 글자</h3><label className="range-label">선 두께<span>{style.lineWidth} px</span></label><Slider aria-label="선 두께" value={[style.lineWidth]} min={1} max={5} step={.25} onValueChange={v=>setStyle({...style,lineWidth:v[0]})}/><label className="range-label">글자 크기<span>{style.fontSize} px</span></label><Slider aria-label="글자 크기" value={[style.fontSize]} min={16} max={32} step={1} onValueChange={v=>setStyle({...style,fontSize:v[0]})}/><p className="math-font-note">수식·숫자·단위는 KaTeX로 조판합니다.</p><Select value={style.font} onValueChange={v=>setStyle({...style,font:v as Style['font']})}><SelectTrigger className="full" aria-label="한글 글꼴"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="serif">한글 · 명조</SelectItem><SelectItem value="sans">한글 · 고딕</SelectItem></SelectContent></Select></section><section className="setting-section"><h3>표시 옵션</h3><label className="switch-row">점선 보조선<Switch checked={style.guides} onCheckedChange={v=>setStyle({...style,guides:v})}/></label><label className="switch-row">축 화살표<Switch checked={style.arrows} onCheckedChange={v=>setStyle({...style,arrows:v})}/></label><label className="switch-row">투명 배경<Switch checked={style.transparent} onCheckedChange={v=>setStyle({...style,transparent:v})}/></label></section><div className="export-card"><div className="export-card-heading"><FileText size={19}/><h3>문항에 바로 넣으세요</h3></div><p>SVG는 선명하게, PNG는 간편하게.</p><div className="export-selects"><Select value={format} onValueChange={setFormat}><SelectTrigger aria-label="다운로드 형식"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="svg">SVG 벡터</SelectItem><SelectItem value="png">PNG 이미지</SelectItem></SelectContent></Select>{format==='png'&&<Select value={scale} onValueChange={setScale}><SelectTrigger aria-label="PNG 해상도"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">1배</SelectItem><SelectItem value="2">2배</SelectItem><SelectItem value="3">3배</SelectItem><SelectItem value="4">4배</SelectItem></SelectContent></Select>}</div><button className="button full" onClick={download} disabled={exporting}><Download size={15}/>다운로드</button></div></aside></main>
 {library&&<GraphLibrary onSelect={next=>{commit(next);setRefine(false);toast.success('기출 유형을 불러왔습니다. 점과 글자를 자유롭게 편집하세요.');}} onClose={()=>setLibrary(false)} onReturnFocus={()=>libraryButton.current?.focus()}/>}
 {apiSettings&&<ApiKeyDialog connected={ready} onConnect={key=>{apiKey.current=key;setReady(true);setError('');toast.success('이 탭에서 사용할 키를 설정했습니다.');}} onDisconnect={()=>{apiKey.current='';request.current?.abort('cancel');setReady(false);}} onClose={()=>setApiSettings(false)}/>}<StudioFooter/>{editor&&<GraphEditor graph={graph} onSave={commit} onClose={()=>setEditor(false)}/>}<Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>설명에서 문항까지</DialogTitle><DialogDescription>도해로 시험지에 넣을 그래프를 만드는 방법입니다.</DialogDescription></DialogHeader><ol className="help-list"><li><b>설명 또는 이미지 입력</b><p>축 이름, 중요한 좌표, 필요한 점선을 구체적으로 적으면 더 정확해집니다.</p></li><li><b>결과 확인과 수정</b><p>미리보기의 점·선·문자를 드래그하거나 축·눈금을 클릭해 수정하세요. 점 추가를 켠 뒤 선 위를 클릭하면 중간에 점이 삽입됩니다. 음영 추가에서 영역과 채우기를 고를 수 있습니다. 좌표 맞춤과 방향키로 정밀하게 조절하고 실행 취소로 되돌릴 수 있습니다. 현재 그래프 수정 옵션을 켜면 설명으로도 수정할 수 있습니다.</p></li><li><b>원하는 형식으로 저장</b><p>인쇄용 벡터는 SVG, 한글·워드에 넣는 그림은 PNG 3배를 사용하세요. 수식은 KaTeX로 조판한 글자 모양을 벡터로 저장하므로 글꼴 설치 없이 유지됩니다. 한글은 기기의 글꼴에 따라 달라질 수 있습니다.</p></li></ol><p className="notice">수치가 없는 그림은 개형을 재현합니다. 생성된 그래프를 문항에 사용하기 전에 조건과 기호를 확인해 주세요.</p></DialogContent></Dialog></div>;
}
