'use client';
import {useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {CurveConnection} from '@/components/curve-connection';
import {CurveLineStyle} from '@/components/curve-line-style';
import {CurvePointInsert} from '@/components/curve-point-insert';
import {DistributionControls} from '@/components/distribution-controls';
import {ConicControls} from '@/components/conic-controls';
import {GraphShading} from '@/components/graph-shading';
import {insertCurvePoint,removeCurve,replaceCurve} from '@/lib/graph-edit';
import {graphSchema,parseCoordinates,curveLineStyle,type Graph,type YAxis} from '@/lib/graph';
import './graph-editor.css';
function connectionPoints(input:string){try{return /^\s*\([^()]+\)\s*$/.test(input)?parseCoordinates(input+','+input,true).slice(0,1):parseCoordinates(input,true);}catch{return null;}}
const coords=(g:Graph)=>g.curves.map(c=>c.points.map(p=>`(${p.x}, ${p.y})`).join(', '));
const guideText=(g:Graph)=>g.guides.map(l=>`${l.x1}, ${l.y1}, ${l.x2}, ${l.y2}${l.yAxis==='right'?', right':''}`).join('\n');
function parseGuides(value:string):Graph['guides']{return value.trim()?value.split('\n').filter(l=>l.trim()).map(l=>{const parts=l.split(',').map(v=>v.trim());const v=parts.slice(0,4).map(Number);const axis=parts[4];if((parts.length!==4&&parts.length!==5)||parts.slice(0,4).some(x=>!x)||v.some(x=>!Number.isFinite(x))||(axis!==undefined&&axis!=='left'&&axis!=='right'))throw Error('보조선은 x1, y1, x2, y2 형태로 적고, 오른쪽 축을 쓰면 끝에 , right를 붙여 주세요.');return {x1:v[0],y1:v[1],x2:v[2],y2:v[3],...(axis?{yAxis:axis as YAxis}:{})};}):[];}
function AxisAssignment({value,rightEnabled,onChange,label='기준 세로축'}:{value?:YAxis;rightEnabled:boolean;onChange:(axis:YAxis)=>void;label?:string}){return <label className="axis-assignment">{label}<select value={value??'left'} onChange={e=>onChange(e.target.value as YAxis)}><option value="left">왼쪽 세로축</option><option value="right" disabled={!rightEnabled}>오른쪽 세로축{!rightEnabled?' (축·눈금에서 추가)':''}</option></select></label>;}

const tickText=(items:Graph['xTicks'])=>items.map(t=>`${t.value} = ${t.label.replace(/\n/g,'\\n')}`).join('\n');
function parseTicks(s:string){return s.trim()?s.split('\n').filter(l=>l.trim()).map(line=>{const i=line.indexOf('=');if(i<0)throw Error('눈금은 값 = 표시 형태로 적어 주세요.');return {value:Number(line.slice(0,i).trim()),label:line.slice(i+1).trim().replace(/\\n/g,'\n')};}):[];}
export function GraphEditor({graph,follow,onFollowChange,onSave,onClose}:{graph:Graph;follow:boolean;onFollowChange:(value:boolean)=>void;onSave:(g:Graph)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(graph));const [points,setPoints]=useState(()=>coords(graph));const [xt,setXt]=useState(()=>tickText(graph.xTicks)),[yt,setYt]=useState(()=>tickText(graph.yTicks));const [rt,setRt]=useState(()=>tickText(graph.rightYAxis?.ticks??[]));const [guides,setGuides]=useState(()=>guideText(graph));const [error,setError]=useState('');
 function save(){try{
  let next:Graph={...draft,xTicks:parseTicks(xt),yTicks:parseTicks(yt),rightYAxis:draft.rightYAxis?{...draft.rightYAxis,ticks:parseTicks(rt)}:draft.rightYAxis,guides:parseGuides(guides)};
  if(next.shadings?.some(shade=>shade.mode==='between'&&(next.curves[shade.curve]?.yAxis??'left')!==(next.curves[shade.otherCurve!]?.yAxis??'left')))throw Error('두 선 사이 음영은 같은 세로축의 선끼리만 사용할 수 있습니다. 두 선의 기준 세로축을 같게 설정하거나 해당 음영을 삭제해 주세요.');
  for(let i=0;i<draft.curves.length;i++){
   const c=draft.curves[i];if(c.distribution||c.conic)continue;
   const parsed=connectionPoints(points[i]);if(!parsed)throw Error('좌표 형식을 확인해 주세요.');
   next=replaceCurve(next,i,{...c,points:parsed},follow);
  }
  const valid=graphSchema.safeParse(next);if(!valid.success)throw Error('좌표·범위·눈금을 확인해 주세요. 선은 12개, 눈금은 축별 30개, 보조선은 80개까지 가능합니다.');
  onSave(valid.data);onClose();
 }catch(e){setError(e instanceof Error?e.message:'값을 확인해 주세요.');}}
 function insertPoint(i:number,segment:number){try{const parsed=connectionPoints(points[i]);if(!parsed)throw Error('먼저 좌표 입력을 마쳐 주세요.');const pending=replaceCurve({...draft,guides:parseGuides(guides)},i,{...draft.curves[i],points:parsed},follow);const result=insertCurvePoint(pending,i,segment,.5);setDraft(result.graph);setGuides(guideText(result.graph));setPoints(p=>p.map((v,j)=>j===i?coords(result.graph)[i]:v));setError('');}catch(e){setError(e instanceof Error?e.message:'점을 추가할 수 없습니다.');}}
 const changeCurve=(i:number,k:string,v:unknown)=>setDraft(d=>({...d,curves:d.curves.map((c,j)=>j===i?{...c,[k]:v}:c),...(k==='yAxis'?{shadings:d.shadings?.map(s=>s.mode!=='rectangle'&&s.curve===i?{...s,yAxis:undefined}:s)}:{})}));
 function updateFormulaCurve(i:number,curve:Graph['curves'][number]){
  try{
   const previous=draft.curves[i],parsed=connectionPoints(points[i]);
   if(!previous.distribution&&!previous.conic&&(curve.distribution||curve.conic)&&!parsed)throw Error('먼저 좌표 입력을 마쳐 주세요.');
   const before={...draft,xTicks:parseTicks(xt),yTicks:parseTicks(yt),rightYAxis:draft.rightYAxis?{...draft.rightYAxis,ticks:parseTicks(rt)}:draft.rightYAxis,guides:parseGuides(guides),equalAxes:draft.rightYAxis?false:!previous.conic&&curve.conic?true:previous.conic&&!curve.conic&&draft.equalAxes===undefined?true:draft.equalAxes};
   const next=replaceCurve(before,i,curve,follow);
   setDraft(next);setGuides(guideText(next));setXt(tickText(next.xTicks));setYt(tickText(next.yTicks));setRt(tickText(next.rightYAxis?.ticks??[]));
   setPoints(values=>values.map((value,j)=>i===j?curve.points.map(point=>`(${point.x}, ${point.y})`).join(', '):value));
   setError('');
  }catch(e){setError(e instanceof Error?e.message:'입력 값을 확인해 주세요.');}
 }
 function toggleRightAxis(enabled:boolean){
  try{
   if(!enabled){
    const references=draft.curves.some(c=>c.yAxis==='right')||draft.labels.some(l=>l.yAxis==='right')||parseGuides(guides).some(g=>g.yAxis==='right')||draft.shadings?.some(s=>s.mode==='rectangle'&&s.yAxis==='right');
    if(references)throw Error('오른쪽 축을 사용하는 선·문자·보조선·사각형 음영의 기준 세로축을 왼쪽으로 바꾼 뒤 오른쪽 축을 꺼 주세요.');
   }
   setDraft(d=>({...d,equalAxes:enabled?false:d.equalAxes,rightYAxis:enabled?{label:'오른쪽 변인',min:0,max:100,ticks:[{value:0,label:'0'},{value:50,label:'50'},{value:100,label:'100'}]}:null}));
   if(enabled)setRt('0 = 0\n50 = 50\n100 = 100');
   setError('');
  }catch(e){setError(e instanceof Error?e.message:'축 설정을 확인해 주세요.');}
 }

 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>그래프 세부 편집</DialogTitle><DialogDescription>좌표와 기호를 바꾸고 적용하면 미리보기에 반영됩니다.</DialogDescription></DialogHeader><Tabs defaultValue="curves"><TabsList className="editor-tabs"><TabsTrigger value="curves">그래프 선</TabsTrigger><TabsTrigger value="axes">축·눈금</TabsTrigger><TabsTrigger value="labels">문자·점선</TabsTrigger><TabsTrigger value="shading">음영</TabsTrigger></TabsList><div className="editor-body"><TabsContent value="curves"><label className="equal-axes-control"><input type="checkbox" checked={follow} onChange={e=>onFollowChange(e.target.checked)}/>보조선·문자 함께 이동</label><p className="hint">좌표는 (x, y)로 입력합니다. 원본에 수치가 없으면 상대적인 좌표를 사용하세요.</p>{draft.curves.map((c,i)=><div className="curve-editor" key={i}><div className="curve-top"><input aria-label={`곡선 ${i+1} 이름`} value={c.name} onChange={e=>changeCurve(i,'name',e.target.value)} maxLength={40}/><button className="icon-button" aria-label={`곡선 ${i+1} 삭제`} onClick={()=>{try{setDraft(removeCurve(draft,i));setPoints(p=>p.filter((_,j)=>i!==j));setError('');}catch(e){setError(e instanceof Error?e.message:'입력 값을 확인해 주세요.');}}}><Trash2 size={16}/></button></div><AxisAssignment value={c.yAxis} rightEnabled={Boolean(draft.rightYAxis)} label={`곡선 ${i+1} 기준 세로축`} onChange={axis=>changeCurve(i,'yAxis',axis)}/>{draft.rightYAxis&&<p className="hint">좌표값은 유지하고 선택한 축의 눈금으로 표시합니다.</p>}{!c.conic&&<DistributionControls curve={c.distribution?c:{...c,points:connectionPoints(points[i])??c.points}} onChange={curve=>updateFormulaCurve(i,curve)}/>}
 <ConicControls curve={(c.distribution||c.conic)?c:{...c,points:connectionPoints(points[i])??c.points}} onChange={curve=>updateFormulaCurve(i,curve)}/>
 {!c.distribution&&!c.conic&&<><label className="field-label">좌표<textarea rows={3} value={points[i]} onChange={e=>setPoints(p=>p.map((v,j)=>i===j?e.target.value:v))}/></label><CurveConnection points={connectionPoints(points[i])} smooth={c.smooth} onChange={value=>changeCurve(i,'smooth',value)}/></>}<CurveLineStyle value={curveLineStyle(c)} onChange={lineStyle=>setDraft(d=>({...d,curves:d.curves.map((curve,j)=>j===i?{...curve,lineStyle,dashed:lineStyle!=='solid'}:curve)}))}/>{!c.distribution&&!c.conic&&<><CurvePointInsert points={connectionPoints(points[i])} onInsert={segment=>insertPoint(i,segment)}/><div className="curve-options">{([['dots','점 표시'],['arrows','진행 방향']] as const).map(([k,l])=><label key={k}>{l}<Switch size="sm" checked={c[k]} onCheckedChange={v=>changeCurve(i,k,v)}/></label>)}</div></>}</div>)}<button className="button" disabled={draft.curves.length>=12} onClick={()=>{setDraft(d=>({...d,curves:[...d.curves,{name:'새 선',points:[{x:0,y:0},{x:1,y:1}],dashed:false,smooth:false,dots:false,arrows:false}]}));setPoints(p=>[...p,'(0, 0), (1, 1)']);}}><Plus size={15}/>선 추가</button></TabsContent>
 <TabsContent value="shading"><GraphShading graph={{...draft,curves:draft.curves.map((c,i)=>(c.distribution||c.conic)?c:({...c,points:connectionPoints(points[i])??c.points}))}} onChange={next=>setDraft(d=>({...d,shadings:next.shadings}))}/><p className="hint">마지막에 변경 적용을 누르면 음영도 함께 반영됩니다.</p></TabsContent>
 <TabsContent value="axes"><label className="field-label">그래프 이름<input maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="equal-axes-control"><input type="checkbox" checked={!draft.rightYAxis&&(draft.equalAxes??draft.curves.some(curve=>Boolean(curve.conic)))} disabled={Boolean(draft.rightYAxis)} onChange={e=>setDraft(d=>({...d,equalAxes:e.target.checked}))}/>가로·세로 같은 축척</label><p className="hint">{draft.rightYAxis?'두 세로축을 사용할 때에는 축마다 독립적인 눈금을 사용합니다.':'같은 좌표 간격을 가로·세로에서 같은 길이로 표시합니다.'}</p><div className="two-columns">{(['x','y'] as const).map(a=><section key={a}><h3>{a==='x'?'가로':'세로'}축</h3><label className="field-label">이름<textarea rows={2} maxLength={80} value={draft[a==='x'?'xLabel':'yLabel']} onChange={e=>setDraft({...draft,[a==='x'?'xLabel':'yLabel']:e.target.value})}/></label><div className="two-columns">{(['Min','Max'] as const).map(v=><label className="field-label" key={v}>{v==='Min'?'최솟값':'최댓값'}<input type="number" step="any" value={draft[`${a}${v}`]} onChange={e=>setDraft({...draft,[`${a}${v}`]:Number(e.target.value)})}/></label>)}</div><label className="field-label">눈금<textarea rows={7} value={a==='x'?xt:yt} onChange={e=>a==='x'?setXt(e.target.value):setYt(e.target.value)}/></label><p className="hint">실제 좌표 = 표시할 문자<br/>예: 2 = 2t_0</p></section>)}</div><section className="right-axis-editor"><label className="equal-axes-control"><input type="checkbox" checked={Boolean(draft.rightYAxis)} onChange={e=>toggleRightAxis(e.target.checked)}/>오른쪽 세로축 사용</label><p className="hint">서로 단위가 다른 두 변인을 비교할 때 사용합니다. 그래프 선에서 각 선의 기준 세로축을 선택하세요.</p>{draft.rightYAxis&&<><label className="field-label">오른쪽 세로축 이름<textarea rows={2} maxLength={80} value={draft.rightYAxis.label} onChange={e=>setDraft(d=>({...d,rightYAxis:{...d.rightYAxis!,label:e.target.value}}))}/></label><div className="two-columns">{(['min','max'] as const).map(k=><label className="field-label" key={k}>오른쪽 축 {k==='min'?'최솟값':'최댓값'}<input type="number" step="any" value={draft.rightYAxis![k]} onChange={e=>setDraft(d=>({...d,rightYAxis:{...d.rightYAxis!,[k]:Number(e.target.value)}}))}/></label>)}</div><label className="field-label">오른쪽 세로축 눈금<textarea rows={5} value={rt} onChange={e=>setRt(e.target.value)}/></label><p className="hint">실제 좌표 = 표시할 문자 · 예: 100 = 100</p></>}</section></TabsContent>
 <TabsContent value="labels"><h3>그래프 안의 문자</h3><p className="hint">x, y는 좌표, 가로·세로 이동은 글자 위치를 조정하는 px 값입니다.</p>{draft.labels.map((l,i)=><div className="label-editor with-axis" key={i}><input aria-label={`문자 ${i+1}`} value={l.text} maxLength={120} onChange={e=>setDraft(d=>({...d,labels:d.labels.map((v,j)=>i===j?{...v,text:e.target.value}:v)}))}/>{(['x','y','dx','dy'] as const).map(k=><label key={k}>{({x:'x',y:'y',dx:'가로 이동',dy:'세로 이동'})[k]}<input type="number" step="any" value={l[k]} onChange={e=>setDraft(d=>({...d,labels:d.labels.map((v,j)=>i===j?{...v,[k]:Number(e.target.value)}:v)}))}/></label>)}<AxisAssignment value={l.yAxis} rightEnabled={Boolean(draft.rightYAxis)} label={`문자 ${i+1} 기준 세로축`} onChange={axis=>setDraft(d=>({...d,labels:d.labels.map((v,j)=>i===j?{...v,yAxis:axis}:v)}))}/><button className="icon-button" aria-label={`문자 ${i+1} 삭제`} onClick={()=>setDraft(d=>({...d,labels:d.labels.filter((_,j)=>i!==j)}))}><Trash2 size={15}/></button></div>)}<button className="button" disabled={draft.labels.length>=40} onClick={()=>setDraft(d=>({...d,labels:[...d.labels,{x:1,y:1,text:'A',dx:0,dy:-15}]}))}><Plus size={15}/>문자 추가</button><label className="field-label guide-input">점선 보조선<textarea rows={7} value={guides} onChange={e=>setGuides(e.target.value)}/></label><p className="hint">한 줄에 시작 x, 시작 y, 끝 x, 끝 y를 적습니다. 오른쪽 축 기준 보조선은 끝에 , right를 붙이세요.<br/>예: 2, 0, 2, 80, right</p></TabsContent></div></Tabs>{error&&<div role="alert" className="error">{error}</div>}<div className="dialog-actions"><button className="button" onClick={onClose}>취소</button><button className="button primary" onClick={save}>변경 적용</button></div></DialogContent></Dialog>;
}
