'use client';
import {useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {CurveConnection} from '@/components/curve-connection';
import {CurveLineStyle} from '@/components/curve-line-style';
import {CurvePointInsert} from '@/components/curve-point-insert';
import {DistributionControls} from '@/components/distribution-controls';
import {GraphShading} from '@/components/graph-shading';
import {insertCurvePoint,removeCurve} from '@/lib/graph-edit';
import {graphSchema,parseCoordinates,curveLineStyle,type Graph} from '@/lib/graph';
function connectionPoints(input:string){try{return /^\s*\([^()]+\)\s*$/.test(input)?parseCoordinates(input+','+input,true).slice(0,1):parseCoordinates(input,true);}catch{return null;}}
const coords=(g:Graph)=>g.curves.map(c=>c.points.map(p=>`(${p.x}, ${p.y})`).join(', '));
const tickText=(items:Graph['xTicks'])=>items.map(t=>`${t.value} = ${t.label.replace(/\n/g,'\\n')}`).join('\n');
function parseTicks(s:string){return s.trim()?s.split('\n').filter(l=>l.trim()).map(line=>{const i=line.indexOf('=');if(i<0)throw Error('눈금은 값 = 표시 형태로 적어 주세요.');return {value:Number(line.slice(0,i).trim()),label:line.slice(i+1).trim().replace(/\\n/g,'\n')};}):[];}
export function GraphEditor({graph,onSave,onClose}:{graph:Graph;onSave:(g:Graph)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(graph));const [points,setPoints]=useState(()=>coords(graph));const [xt,setXt]=useState(()=>tickText(graph.xTicks)),[yt,setYt]=useState(()=>tickText(graph.yTicks));const [guides,setGuides]=useState(()=>graph.guides.map(l=>`${l.x1}, ${l.y1}, ${l.x2}, ${l.y2}`).join('\n'));const [error,setError]=useState('');
 function save(){try{const next={...draft,xTicks:parseTicks(xt),yTicks:parseTicks(yt),curves:draft.curves.map((c,i)=>c.distribution?c:({...c,points:c.points.length===1&&/^\s*\([^()]+\)\s*$/.test(points[i])?parseCoordinates(points[i]+','+points[i],true).slice(0,1):parseCoordinates(points[i],true)})),guides:guides.trim()?guides.split('\n').filter(Boolean).map(l=>{const v=l.split(',').map(Number);if(v.length!==4||v.some(x=>!Number.isFinite(x)))throw Error('보조선은 x1, y1, x2, y2 형태로 적어 주세요.');return {x1:v[0],y1:v[1],x2:v[2],y2:v[3]};}):[]};const valid=graphSchema.safeParse(next);if(!valid.success)throw Error(valid.error.issues[0]?.message==='축의 최댓값은 최솟값보다 커야 합니다.'?valid.error.issues[0].message:'좌표·범위·눈금을 확인해 주세요. 선은 12개, 눈금은 축별 30개, 보조선은 80개까지 가능합니다.');onSave(valid.data);onClose();}catch(e){setError(e instanceof Error?e.message:'값을 확인해 주세요.');}}
 function insertPoint(i:number,segment:number){try{const parsed=connectionPoints(points[i]);if(!parsed)throw Error('먼저 좌표 입력을 마쳐 주세요.');const result=insertCurvePoint({...draft,curves:draft.curves.map((c,j)=>j===i?{...c,points:parsed}:c)},i,segment,.5);setDraft(result.graph);setPoints(p=>p.map((v,j)=>j===i?coords(result.graph)[i]:v));setError('');}catch(e){setError(e instanceof Error?e.message:'점을 추가할 수 없습니다.');}}
 const changeCurve=(i:number,k:string,v:unknown)=>setDraft(d=>({...d,curves:d.curves.map((c,j)=>j===i?{...c,[k]:v}:c)}));
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>그래프 세부 편집</DialogTitle><DialogDescription>좌표와 기호를 바꾸고 적용하면 미리보기에 반영됩니다.</DialogDescription></DialogHeader><Tabs defaultValue="curves"><TabsList className="editor-tabs"><TabsTrigger value="curves">그래프 선</TabsTrigger><TabsTrigger value="axes">축·눈금</TabsTrigger><TabsTrigger value="labels">문자·점선</TabsTrigger><TabsTrigger value="shading">음영</TabsTrigger></TabsList><div className="editor-body"><TabsContent value="curves"><p className="hint">좌표는 (x, y)로 입력합니다. 원본에 수치가 없으면 상대적인 좌표를 사용하세요.</p>{draft.curves.map((c,i)=><div className="curve-editor" key={i}><div className="curve-top"><input aria-label={`곡선 ${i+1} 이름`} value={c.name} onChange={e=>changeCurve(i,'name',e.target.value)} maxLength={40}/><button className="icon-button" aria-label={`곡선 ${i+1} 삭제`} onClick={()=>{try{setDraft(removeCurve(draft,i));setPoints(p=>p.filter((_,j)=>i!==j));setError('');}catch(e){setError(e instanceof Error?e.message:'입력 값을 확인해 주세요.');}}}><Trash2 size={16}/></button></div><DistributionControls curve={c.distribution?c:{...c,points:connectionPoints(points[i])??c.points}} onChange={curve=>{if(!c.distribution&&curve.distribution&&!connectionPoints(points[i])){setError('먼저 좌표 입력을 마쳐 주세요.');return;}setDraft(d=>({...d,curves:d.curves.map((value,j)=>i===j?curve:value)}));setPoints(previous=>previous.map((value,j)=>i===j?curve.points.map(point=>`(${point.x}, ${point.y})`).join(', '):value));setError('');}}/>{!c.distribution&&<><label className="field-label">좌표<textarea rows={3} value={points[i]} onChange={e=>setPoints(p=>p.map((v,j)=>i===j?e.target.value:v))}/></label><CurveConnection points={connectionPoints(points[i])} smooth={c.smooth} onChange={value=>changeCurve(i,'smooth',value)}/></>}<CurveLineStyle value={curveLineStyle(c)} onChange={lineStyle=>setDraft(d=>({...d,curves:d.curves.map((curve,j)=>j===i?{...curve,lineStyle,dashed:lineStyle!=='solid'}:curve)}))}/>{!c.distribution&&<><CurvePointInsert points={connectionPoints(points[i])} onInsert={segment=>insertPoint(i,segment)}/><div className="curve-options">{([['dots','점 표시'],['arrows','진행 방향']] as const).map(([k,l])=><label key={k}>{l}<Switch size="sm" checked={c[k]} onCheckedChange={v=>changeCurve(i,k,v)}/></label>)}</div></>}</div>)}<button className="button" disabled={draft.curves.length>=12} onClick={()=>{setDraft(d=>({...d,curves:[...d.curves,{name:'새 선',points:[{x:0,y:0},{x:1,y:1}],dashed:false,smooth:false,dots:false,arrows:false}]}));setPoints(p=>[...p,'(0, 0), (1, 1)']);}}><Plus size={15}/>선 추가</button></TabsContent>
 <TabsContent value="shading"><GraphShading graph={{...draft,curves:draft.curves.map((c,i)=>c.distribution?c:({...c,points:connectionPoints(points[i])??c.points}))}} onChange={setDraft}/><p className="hint">마지막에 변경 적용을 누르면 음영도 함께 반영됩니다.</p></TabsContent>
 <TabsContent value="axes"><label className="field-label">그래프 이름<input maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="two-columns">{(['x','y'] as const).map(a=><section key={a}><h3>{a==='x'?'가로':'세로'}축</h3><label className="field-label">이름<textarea rows={2} maxLength={80} value={draft[a==='x'?'xLabel':'yLabel']} onChange={e=>setDraft({...draft,[a==='x'?'xLabel':'yLabel']:e.target.value})}/></label><div className="two-columns">{(['Min','Max'] as const).map(v=><label className="field-label" key={v}>{v==='Min'?'최솟값':'최댓값'}<input type="number" step="any" value={draft[`${a}${v}`]} onChange={e=>setDraft({...draft,[`${a}${v}`]:Number(e.target.value)})}/></label>)}</div><label className="field-label">눈금<textarea rows={7} value={a==='x'?xt:yt} onChange={e=>a==='x'?setXt(e.target.value):setYt(e.target.value)}/></label><p className="hint">실제 좌표 = 표시할 문자<br/>예: 2 = 2t_0</p></section>)}</div></TabsContent>
 <TabsContent value="labels"><h3>그래프 안의 문자</h3><p className="hint">x, y는 좌표, 가로·세로 이동은 글자 위치를 조정하는 px 값입니다.</p>{draft.labels.map((l,i)=><div className="label-editor" key={i}><input aria-label={`문자 ${i+1}`} value={l.text} maxLength={120} onChange={e=>setDraft(d=>({...d,labels:d.labels.map((v,j)=>i===j?{...v,text:e.target.value}:v)}))}/>{(['x','y','dx','dy'] as const).map(k=><label key={k}>{({x:'x',y:'y',dx:'가로 이동',dy:'세로 이동'})[k]}<input type="number" step="any" value={l[k]} onChange={e=>setDraft(d=>({...d,labels:d.labels.map((v,j)=>i===j?{...v,[k]:Number(e.target.value)}:v)}))}/></label>)}<button className="icon-button" aria-label={`문자 ${i+1} 삭제`} onClick={()=>setDraft(d=>({...d,labels:d.labels.filter((_,j)=>i!==j)}))}><Trash2 size={15}/></button></div>)}<button className="button" disabled={draft.labels.length>=40} onClick={()=>setDraft(d=>({...d,labels:[...d.labels,{x:1,y:1,text:'A',dx:0,dy:-15}]}))}><Plus size={15}/>문자 추가</button><label className="field-label guide-input">점선 보조선<textarea rows={7} value={guides} onChange={e=>setGuides(e.target.value)}/></label><p className="hint">한 줄에 시작 x, 시작 y, 끝 x, 끝 y를 적습니다.</p></TabsContent></div></Tabs>{error&&<div role="alert" className="error">{error}</div>}<div className="dialog-actions"><button className="button" onClick={onClose}>취소</button><button className="button primary" onClick={save}>변경 적용</button></div></DialogContent></Dialog>;
}
